import type { Metadata } from "next";
import { Cormorant_Infant } from "next/font/google";
import localFont from "next/font/local";
import 'leaflet/dist/leaflet.css';
import "./globals.css";

const cormorant = Cormorant_Infant({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-cormorant-infant",
    display: "swap",
});

const helvetica = localFont({
    src: [
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueUltraLight.otf",
            weight: "100",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueUltraLightItalic.otf",
            weight: "100",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueThin.otf",
            weight: "200",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueThinItalic.otf",
            weight: "200",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueLight.otf",
            weight: "300",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueLightItalic.otf",
            weight: "300",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueRoman.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueItalic.ttf",
            weight: "400",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueMedium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueMediumItalic.otf",
            weight: "500",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueBold.otf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueBoldItalic.otf",
            weight: "600",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueHeavy.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueHeavyItalic.otf",
            weight: "700",
            style: "italic",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueBlack.otf",
            weight: "800",
            style: "normal",
        },
        {
            path: "./fonts/HelveticaNeue/HelveticaNeueBlackItalic.otf",
            weight: "800",
            style: "italic",
        },
    ],
    display: "swap",
    variable: "--font-helvetica-neue",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function AppLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${helvetica.variable} ${cormorant.variable} font-helvetica antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
